language: java
jdk: oraclejdk8
script: echo "build..."
deploy:
  env:
  - secure: iqx3dk3gN2eP+5ClIxYmhEZXswhKgC00sqbQsX/2JOxpTm1jcELC+3qzZG/Wb9yhuZoNj9rkbWKPQ7q5fOOoWxSoG/Y3fdvMzOW+bk8urLC3+LXCuuTeZiGjRS9ukK0PCVAom/AKfy/kPK2o4fAlJBmOVTTDwRBP78UaYdT0oNXgn3bRLVbzM4r2vD30B82CPipzkuKJg5CTQQSY/x6C3LQ56S9C7i5BTuMAAp8l3ju137Eb5Ht+b7tU1SAUMNxx+rJtV3ZLgcqYlmhxXKXCGm6ng0PL6N+RDHfbr660MyhFe2ZaKN52f0AoLIwWntCXLOecX2TaGW0GeG/0gi+1A9OrwMpZK5aisoOJKGHzUAErCBZPOjdFNMp76CGSS8p7cYknYoEfCP9DZL4LkYtb6oTC1w/txldXaV3SV4Ox8O0hQA1lkDKM73osnPInlwwleRTbpb2HFMXwdv9kG59P5TZen9Dh88X/jvvImiQ3R9uWj10yWEsGv/vi6PMN7YPLwoHedHE/8YV6HMcsS3C6qMux/XPSCm7A+xnnhNUmn3UglAjmjnOhzOXlGeIsgsQufZEShuobY16xyO0n9/xVIMp8a5oz+MCa+e7k9i8+SpfHNV/H7ct5/gbRjvF3kLM7c180amnNLydAaUcgVv49wqkVp5ptetBR6RmIVib1CLs=
  provider: script
  script: "./test.sh"
